### ISSUE TITLE
Error with Hg 2.5.2, TortoiseHg

### ISSUE THREAD

**Issue by edtate** [ned14/BEurtle#4]
I have a win7 64-bit system with Mercurial 2.5.2 and TortoiseHg 2.7.1. I also have PythonXY 2.7.3.1 installed on this machine. 
I installed BEurtle 1.50 alpha 2.
I configured HG workbench to enable BEurtle as the issue tracker for my project.
When I click on 'Bugs! Bugs! Bugs!' the window for BEurtle appears, but I get a popup with the following message:

Traceback (most recent call last):  File "<string>", line 6, in <module>  File "**main**.py", line 128, in <module>  File "**main__be**.py", line 26, in <module>  File "libbe/ui/command_line.py", line 363, in main  File "libbe/ui/command_line.py", line 284, in dispatch  File "libbe/command/base.py", line 567, in run  File "libbe/command/base.py", line 294, in run  File "libbe\command\list.py", line 128, in _run  File "libbe/command/base.py", line 543, in get_bugdir  File "libbe/command/base.py", line 531, in get_storage  File "libbe/storage/base.py", line 217, in connect  File "libbe/storage/vcs/base.py", line 705, in _connect  File "libbe/storage/vcs/base.py", line 668, in root  File "libbe\storage\vcs\hg.py", line 114, in _vcs_root  File "libbe\storage\vcs\hg.py", line 89, in _u_invoke_client  File "libbe/storage/vcs/base.py", line 572, in version_cmpAttributeError: 'NoneType' object has no attribute 'split'

I am able to clear the pop-up. If I select a path, I get the following error on a pop-up:

Traceback (most recent call last):  File "<string>", line 6, in <module>  File "**main**.py", line 128, in <module>  File "**main__be**.py", line 26, in <module>  File "libbe/ui/command_line.py", line 363, in main  File "libbe/ui/command_line.py", line 284, in dispatch  File "libbe/command/base.py", line 567, in run  File "libbe/command/base.py", line 294, in run  File "libbe\command\list.py", line 128, in _run  File "libbe/command/base.py", line 543, in get_bugdir  File "libbe/command/base.py", line 531, in get_storage  File "libbe/storage/base.py", line 217, in connect  File "libbe/storage/vcs/base.py", line 705, in _connect  File "libbe/storage/vcs/base.py", line 668, in root  File "libbe\storage\vcs\hg.py", line 114, in _vcs_root  File "libbe\storage\vcs\hg.py", line 89, in _u_invoke_client  File "libbe/storage/vcs/base.py", line 572, in version_cmpAttributeError: 'NoneType' object has no attribute 'split'

I am able to clear that pop-up. The new issue button, the delete issue button, and the ok button remain greyed out.

I am able to cancel and return to HgWorkbench.

**Comment by ned14** [comment]
This error suggests that BE (not BEurtle) can't find the Mercurial repository.

Can you get it working with BE on the command line?

Niall

**Comment by edtate** [comment]
If I run BE, by linking back to your install directory, I get the same fault when running in a project directory. I created a directory D:__projects|__test_repo. I initialized it from Hg Workbench. Then did the following:

D:__projects>cd __test_repo

D:__projects__test_repo>"C:\Program Files (x86)\ned Productions Limited\BEurtle\dist\be.exe" init
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "**main__be**.py", line 26, in <module>
  File "libbe/ui/command_line.py", line 363, in main
  File "libbe/ui/command_line.py", line 284, in dispatch
  File "libbe/command/base.py", line 567, in run
  File "libbe/command/base.py", line 294, in run
  File "libbe\command\init.py", line 91, in _run
  File "libbe/storage/base.py", line 217, in connect
  File "libbe/storage/vcs/base.py", line 705, in _connect
  File "libbe/storage/vcs/base.py", line 668, in root
  File "libbe\storage\vcs\hg.py", line 114, in _vcs_root
  File "libbe\storage\vcs\hg.py", line 89, in _u_invoke_client
  File "libbe/storage/vcs/base.py", line 572, in version_cmp
AttributeError: 'NoneType' object has no attribute 'split'

D:__projects__test_repo>"C:\Program Files (x86)\ned Productions Limited\BEurtle\dist\be.exe" help
usage: be [options] [COMMAND [command-options] [COMMAND-ARGS ...]]

Options:
  -h, --help            Print a help message.

  --complete            Print a list of possible completions.

  --version             Print version string.

  --full-version        Print full version information.

  -r REPO, --repo=REPO  Select BE repository (see `be help repo`) rather than
                        the current directory.

  --paginate            Pipe all output into less (or if set, $PAGER).

  --no-pager            Do not pipe git output into a pager.

Bugs Everywhere - Distributed bug tracking

Supported commands
be assign        Assign an individual or group to fix a bug
be comment       Add a comment to a bug
be commit        Commit the currently pending changes to the repository
be depend        Add/remove bug dependencies
be diff          Compare bug reports with older tree
be due           Set bug due dates
be gui           Opens a GUI for issue management
be help          Print help for given command or topic
be html          Generate a static HTML dump of the current repository status
be import_xml    Import comments and bugs from XML
be init          Create an on-disk bug repository
be list          List bugs
be merge         Merge duplicate bugs
be new           Create a new bug
be remove        Remove (delete) a bug and its comments
be serve         Serve bug directory storage over HTTP.
be set           Change bug directory settings
be severity      Change a bug's severity level
be show          Show a particular bug, comment, or combination of both.
be status        Change a bug's status level
be subscribe     (Un)subscribe to change notification
be tag           Tag a bug, or search bugs for tags
be target        Assorted bug target manipulations and queries
be vcs           Perform an operation to the underlying VCS

Run
  be help [command]
for more information.

D:__projects__test_repo>

---

Note: I did some work on another machine with BE source and had a similar problem. To fix it, I had to add mercurial to my python distribution. Once I did that, I could initiatize, add, etc issues to the repo.

**Comment by edtate** [comment]
Hit the wrong button.

**Comment by ned14** [comment]
Ok, so the fix is to add the mercurial module to the bundled python distribution. I'll add that to the next release. Thanks. Niall

**Comment by yallie** [comment]
Hi!
I've got the same issue :)
Any plans to release an update?

**Comment by ned14** [comment]
Yeah sorry about dropping the ball on this. I've had a lot of life events. Right now all my belongings, including my dev machine, are currently stuck in a container in Montreal, so there definitely won't be any movement until that arrives. Sorry, Niall
